### ISSUE TITLE
Repository doesn't match 0.2.0.1 release on Hackage

### ISSUE THREAD

**Issue by bgamari** [UU-ComputerScience/uu-interleaved#1]
The most recent version on Hackage doesn't appear to be available from version control.

**Comment by doaitse** [comment]
Hi,

I had updated the Home page info, but not the Repository info. I just did. As far as I can see the version on hackage  compiles with the latest GHC:

Doaitse-2:~ doaitse$ ghc-pkg --version
GHC package manager version 8.4.3
Doaitse-2:uu-interleaved doaitse$ cabal configure
Warning: The package list for 'hackage.haskell.org' is 16 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Configuring uu-interleaved-0.2.0.1...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Doaitse-2:uu-interleaved doaitse$ cabal build
Building uu-interleaved-0.2.0.1...
Preprocessing library uu-interleaved-0.2.0.1...
Doaitse-2:uu-interleaved doaitse$ 


If problems remain please let me know,

 Best,
 Doaitse

**Comment by bgamari** [comment]
The latest version does indeed build with 8.4. However, it doesn't with 8.2 (see #2) and the uploaded tarball does not match what is available on `master`.

**Comment by doaitse** [comment]
I hav merged your updates into a new minor version and uploaded it to Hackage
